version: '3.8'

services:
  web:
    build: .
    # Прокидаємо порт: зліва (8000) - ваш комп'ютер, справа (8000) - всередині контейнера
    ports:
      - "8000:8000"
    # Змінні оточення для продакшену
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=127.0.0.1,localhost,0.0.0.0
    volumes:
      # Зберігаємо базу даних SQLite, щоб вона не зникала після перезапуску
      - ./db.sqlite3:/app/db.sqlite3